### ISSUE TITLE
Working together on ansible-role-tinc?

### ISSUE THREAD

**Issue by evrardjp** [rlex/ansible-role-tinc#2]
Hello, 

I also have a tinc role, should we work together and merge them?
https://github.com/evrardjp/ansible-tinc

**Comment by rlex** [comment]
This role was quickly hacked together from other unsupported role, and opensourced only because friend asked for it 
I don't feel like i want to work on it, especially with tinc 1.1 somewhere on horizon with completely different node authorization system, so in current state it "just works" with 1.0 branch. 
But feel free to grab any parts of code you find usable.
